<?php
namespace common\models;

/**
 * Class Setting
 * @package common\models
 */
class Setting extends BaseModel
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return '{{%am_setting}}';
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /*
     *
     */
    public function attributeLabels()
    {
        return [
            'type' => '类型',
            'name' => '名称',
            'item' => '键名',
            'value' => '键值',
            'info' => '简介'
        ];
    }

    /**
     * 获取配置信息
     * @param string $label
     * @return null|static
     */
    public static function getConfInfo($label = ''){
        return static::findOne(['item' => $label]);
    }
}